@SERVICE_URL=http://localhost:4004/odata/v4/main


GET {{SERVICE_URL}}/SaledOrderHeaders
Content-Type: application/json


###
POST {{SERVICE_URL}}/SaledOrderHeaders
Content-Type: application/json

{
    "id": "1234"
}


###
DELETE {{SERVICE_URL}}/SaledOrderHeaders(id='1234')
Content-Type: application/json

{}

###
DELETE {{SERVICE_URL}}/SaledOrderHeaders(id='1234')
Content-Type: application/json

{}