@SERVICE_URL=http://localhost:4004/odata/v4/main
@ID=781c9afa-098e-4131-98c4-72c0a72e24ad
@CUSTOMER_ID=fe035692-97f2-47d7-8f19-85ad85e525c1
@PRODUCT_ID=f0ca9b92-17a3-475b-b567-71bbd363d1d1

GET {{SERVICE_URL}}/SaledOrderHeaders
Content-Type: application/json

###
POST {{SERVICE_URL}}/SaledOrderHeaders
Content-Type: application/json

{
 "id": "{{ID}}",
  "customer_id": "{{CUSTOMER_ID}}",
  "items" : [
    {
        "header_id": "{{ID}}",
        "product_id": "{{PRODUCT_ID}}",
        "quantity": 10,
        "price": 1.99
    }
  ]
}

###
POST {{SERVICE_URL}}/SaledOrderHeaders
Content-Type: application/json

{

}



###
GET {{SERVICE_URL}}/SaledOrderHeaders(id={{ID}})
Content-Type: application/json


###
GET {{SERVICE_URL}}/SaledOrderHeaders(id={{ID}})?$expand=items
Content-Type: application/json


###
PUT {{SERVICE_URL}}/SaledOrderHeaders(id={{ID}})
Content-Type: application/json

{

}

###
DELETE {{SERVICE_URL}}/SaledOrderHeaders(id={{ID}})
Content-Type: application/json


###
# Filter
GET {{SERVICE_URL}}/SaledOrderHeaders?$filter=customer/id eq fe035692-97f2-47d7-8f19-85ad85e525c1
Content-Type: application/json

###
# Expand
GET {{SERVICE_URL}}/SaledOrderHeaders?$expand=customer(),items($expand=product;$filter=product/price gt 0)
Content-Type: application/json

###
# Select
GET {{SERVICE_URL}}/SaledOrderHeaders?$expand=customer($select=firstName,lastName),items($expand=product($select=name);$filter=product/price gt 0)&$select=totalAmount
Content-Type: application/json

###
# Count
GET {{SERVICE_URL}}/SaledOrderHeaders/$count
Content-Type: application/json

###
GET {{SERVICE_URL}}/SaledOrderHeaders/$count?$expand=customer($select=firstName,lastName),items($expand=product($select=name);$filter=product/price gt 0)&$select=totalAmount
Content-Type: application/json

###
# Skip - Pular
# Top  - Quantidade
GET {{SERVICE_URL}}/SaledOrderHeaders?$skip=5&$top=2
Content-Type: application/json

###
# Search
GET {{SERVICE_URL}}/SaledOrderHeaders?$search=Marcelo
Content-Type: application/json
